//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.22 at 01:45:09 PM EST 
//


package uk.org.siri.siri;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import uk.org.ifopt.ifopt.LinkProjectionStructure;


/**
 * Summary information about a stop within line 
 * 
 * <p>Java class for StopPointInPatternStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopPointInPatternStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siri.org.uk/siri}AnnotatedStopPointStructure">
 *       &lt;sequence>
 *         &lt;element name="Order" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="OnwardLinkShape" type="{http://www.siri.org.uk/siri}LineShapeStructure" minOccurs="0"/>
 *         &lt;element name="LinkProjectionToNextStopPoint" type="{http://www.ifopt.org.uk/ifopt}LinkProjectionStructure" minOccurs="0"/>
 *         &lt;element ref="{http://www.siri.org.uk/siri}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopPointInPatternStructure", propOrder = {
    "order",
    "onwardLinkShape",
    "linkProjectionToNextStopPoint",
    "extensions"
})
public class StopPointInPatternStructure
    extends AnnotatedStopPointStructure
{

    @XmlElement(name = "Order", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger order;
    @XmlElement(name = "OnwardLinkShape")
    protected LineShapeStructure onwardLinkShape;
    @XmlElement(name = "LinkProjectionToNextStopPoint")
    protected LinkProjectionStructure linkProjectionToNextStopPoint;
    @XmlElement(name = "Extensions")
    protected ExtensionsStructure extensions;

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

    /**
     * Gets the value of the onwardLinkShape property.
     * 
     * @return
     *     possible object is
     *     {@link LineShapeStructure }
     *     
     */
    public LineShapeStructure getOnwardLinkShape() {
        return onwardLinkShape;
    }

    /**
     * Sets the value of the onwardLinkShape property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineShapeStructure }
     *     
     */
    public void setOnwardLinkShape(LineShapeStructure value) {
        this.onwardLinkShape = value;
    }

    /**
     * Gets the value of the linkProjectionToNextStopPoint property.
     * 
     * @return
     *     possible object is
     *     {@link LinkProjectionStructure }
     *     
     */
    public LinkProjectionStructure getLinkProjectionToNextStopPoint() {
        return linkProjectionToNextStopPoint;
    }

    /**
     * Sets the value of the linkProjectionToNextStopPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkProjectionStructure }
     *     
     */
    public void setLinkProjectionToNextStopPoint(LinkProjectionStructure value) {
        this.linkProjectionToNextStopPoint = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionsStructure }
     *     
     */
    public ExtensionsStructure getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionsStructure }
     *     
     */
    public void setExtensions(ExtensionsStructure value) {
        this.extensions = value;
    }

}
