//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.22 at 01:45:09 PM EST 
//


package eu.datex2.schema._2_0rc1._2_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.datex2.schema._2_0rc1._2_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _D2LogicalModel_QNAME = new QName("http://datex2.eu/schema/2_0RC1/2_0", "d2LogicalModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.datex2.schema._2_0rc1._2_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Itinerary }
     * 
     */
    public Itinerary createItinerary() {
        return new Itinerary();
    }

    /**
     * Create an instance of {@link MultilingualString }
     * 
     */
    public MultilingualString createMultilingualString() {
        return new MultilingualString();
    }

    /**
     * Create an instance of {@link MeasurementSiteRecord }
     * 
     */
    public MeasurementSiteRecord createMeasurementSiteRecord() {
        return new MeasurementSiteRecord();
    }

    /**
     * Create an instance of {@link SiteMeasurements }
     * 
     */
    public SiteMeasurements createSiteMeasurements() {
        return new SiteMeasurements();
    }

    /**
     * Create an instance of {@link D2LogicalModel }
     * 
     */
    public D2LogicalModel createD2LogicalModel() {
        return new D2LogicalModel();
    }

    /**
     * Create an instance of {@link Subjects }
     * 
     */
    public Subjects createSubjects() {
        return new Subjects();
    }

    /**
     * Create an instance of {@link AxleWeight }
     * 
     */
    public AxleWeight createAxleWeight() {
        return new AxleWeight();
    }

    /**
     * Create an instance of {@link RoadsideReferencePointSecondaryLocation }
     * 
     */
    public RoadsideReferencePointSecondaryLocation createRoadsideReferencePointSecondaryLocation() {
        return new RoadsideReferencePointSecondaryLocation();
    }

    /**
     * Create an instance of {@link GenericPublication }
     * 
     */
    public GenericPublication createGenericPublication() {
        return new GenericPublication();
    }

    /**
     * Create an instance of {@link eu.datex2.schema._2_0rc1._2_0.MeasurementSpecificCharacteristics }
     * 
     */
    public eu.datex2.schema._2_0rc1._2_0.MeasurementSpecificCharacteristics createMeasurementSpecificCharacteristics() {
        return new eu.datex2.schema._2_0rc1._2_0.MeasurementSpecificCharacteristics();
    }

    /**
     * Create an instance of {@link WidthCharacteristic }
     * 
     */
    public WidthCharacteristic createWidthCharacteristic() {
        return new WidthCharacteristic();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link ExternalReferencing }
     * 
     */
    public ExternalReferencing createExternalReferencing() {
        return new ExternalReferencing();
    }

    /**
     * Create an instance of {@link NonManagedCause }
     * 
     */
    public NonManagedCause createNonManagedCause() {
        return new NonManagedCause();
    }

    /**
     * Create an instance of {@link SupplementaryPositionalDescription }
     * 
     */
    public SupplementaryPositionalDescription createSupplementaryPositionalDescription() {
        return new SupplementaryPositionalDescription();
    }

    /**
     * Create an instance of {@link PrecipitationDetail }
     * 
     */
    public PrecipitationDetail createPrecipitationDetail() {
        return new PrecipitationDetail();
    }

    /**
     * Create an instance of {@link ElaboratedData }
     * 
     */
    public ElaboratedData createElaboratedData() {
        return new ElaboratedData();
    }

    /**
     * Create an instance of {@link AuthorityOperation }
     * 
     */
    public AuthorityOperation createAuthorityOperation() {
        return new AuthorityOperation();
    }

    /**
     * Create an instance of {@link LocationByReference }
     * 
     */
    public LocationByReference createLocationByReference() {
        return new LocationByReference();
    }

    /**
     * Create an instance of {@link Delays }
     * 
     */
    public Delays createDelays() {
        return new Delays();
    }

    /**
     * Create an instance of {@link LengthCharacteristic }
     * 
     */
    public LengthCharacteristic createLengthCharacteristic() {
        return new LengthCharacteristic();
    }

    /**
     * Create an instance of {@link PredefinedLocationSet }
     * 
     */
    public PredefinedLocationSet createPredefinedLocationSet() {
        return new PredefinedLocationSet();
    }

    /**
     * Create an instance of {@link WeatherRelatedRoadConditions }
     * 
     */
    public WeatherRelatedRoadConditions createWeatherRelatedRoadConditions() {
        return new WeatherRelatedRoadConditions();
    }

    /**
     * Create an instance of {@link PointCoordinates }
     * 
     */
    public PointCoordinates createPointCoordinates() {
        return new PointCoordinates();
    }

    /**
     * Create an instance of {@link MatrixSignSetting }
     * 
     */
    public MatrixSignSetting createMatrixSignSetting() {
        return new MatrixSignSetting();
    }

    /**
     * Create an instance of {@link TrafficView }
     * 
     */
    public TrafficView createTrafficView() {
        return new TrafficView();
    }

    /**
     * Create an instance of {@link InternationalIdentifier }
     * 
     */
    public InternationalIdentifier createInternationalIdentifier() {
        return new InternationalIdentifier();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link OverallPeriod }
     * 
     */
    public OverallPeriod createOverallPeriod() {
        return new OverallPeriod();
    }

    /**
     * Create an instance of {@link AlertCMethod2Linear }
     * 
     */
    public AlertCMethod2Linear createAlertCMethod2Linear() {
        return new AlertCMethod2Linear();
    }

    /**
     * Create an instance of {@link ManagedCause }
     * 
     */
    public ManagedCause createManagedCause() {
        return new ManagedCause();
    }

    /**
     * Create an instance of {@link HazardousMaterials }
     * 
     */
    public HazardousMaterials createHazardousMaterials() {
        return new HazardousMaterials();
    }

    /**
     * Create an instance of {@link LocationCharacteristicsOverride }
     * 
     */
    public LocationCharacteristicsOverride createLocationCharacteristicsOverride() {
        return new LocationCharacteristicsOverride();
    }

    /**
     * Create an instance of {@link AlertCDirection }
     * 
     */
    public AlertCDirection createAlertCDirection() {
        return new AlertCDirection();
    }

    /**
     * Create an instance of {@link CarParks }
     * 
     */
    public CarParks createCarParks() {
        return new CarParks();
    }

    /**
     * Create an instance of {@link UrlLink }
     * 
     */
    public UrlLink createUrlLink() {
        return new UrlLink();
    }

    /**
     * Create an instance of {@link TpegGeometricArea }
     * 
     */
    public TpegGeometricArea createTpegGeometricArea() {
        return new TpegGeometricArea();
    }

    /**
     * Create an instance of {@link PrecipitationInformation }
     * 
     */
    public PrecipitationInformation createPrecipitationInformation() {
        return new PrecipitationInformation();
    }

    /**
     * Create an instance of {@link DayWeekMonth }
     * 
     */
    public DayWeekMonth createDayWeekMonth() {
        return new DayWeekMonth();
    }

    /**
     * Create an instance of {@link MaintenanceVehicles }
     * 
     */
    public MaintenanceVehicles createMaintenanceVehicles() {
        return new MaintenanceVehicles();
    }

    /**
     * Create an instance of {@link IndividualVehicleMeasurements }
     * 
     */
    public IndividualVehicleMeasurements createIndividualVehicleMeasurements() {
        return new IndividualVehicleMeasurements();
    }

    /**
     * Create an instance of {@link TpegSimplePoint }
     * 
     */
    public TpegSimplePoint createTpegSimplePoint() {
        return new TpegSimplePoint();
    }

    /**
     * Create an instance of {@link TrafficViewPublication }
     * 
     */
    public TrafficViewPublication createTrafficViewPublication() {
        return new TrafficViewPublication();
    }

    /**
     * Create an instance of {@link AreaDestination }
     * 
     */
    public AreaDestination createAreaDestination() {
        return new AreaDestination();
    }

    /**
     * Create an instance of {@link VehicleSpeed }
     * 
     */
    public VehicleSpeed createVehicleSpeed() {
        return new VehicleSpeed();
    }

    /**
     * Create an instance of {@link PointByCoordinates }
     * 
     */
    public PointByCoordinates createPointByCoordinates() {
        return new PointByCoordinates();
    }

    /**
     * Create an instance of {@link Wind }
     * 
     */
    public Wind createWind() {
        return new Wind();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link PollutionInformation }
     * 
     */
    public PollutionInformation createPollutionInformation() {
        return new PollutionInformation();
    }

    /**
     * Create an instance of {@link VariableMessageSignSetting }
     * 
     */
    public VariableMessageSignSetting createVariableMessageSignSetting() {
        return new VariableMessageSignSetting();
    }

    /**
     * Create an instance of {@link TpegIlcPointDescriptor }
     * 
     */
    public TpegIlcPointDescriptor createTpegIlcPointDescriptor() {
        return new TpegIlcPointDescriptor();
    }

    /**
     * Create an instance of {@link TrafficHeadway }
     * 
     */
    public TrafficHeadway createTrafficHeadway() {
        return new TrafficHeadway();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link AlertCMethod2PrimaryPointLocation }
     * 
     */
    public AlertCMethod2PrimaryPointLocation createAlertCMethod2PrimaryPointLocation() {
        return new AlertCMethod2PrimaryPointLocation();
    }

    /**
     * Create an instance of {@link Subscription }
     * 
     */
    public Subscription createSubscription() {
        return new Subscription();
    }

    /**
     * Create an instance of {@link RoadSurfaceConditionInformation }
     * 
     */
    public RoadSurfaceConditionInformation createRoadSurfaceConditionInformation() {
        return new RoadSurfaceConditionInformation();
    }

    /**
     * Create an instance of {@link TrafficSpeed }
     * 
     */
    public TrafficSpeed createTrafficSpeed() {
        return new TrafficSpeed();
    }

    /**
     * Create an instance of {@link SituationPublication }
     * 
     */
    public SituationPublication createSituationPublication() {
        return new SituationPublication();
    }

    /**
     * Create an instance of {@link RoadSurfaceConditionMeasurements }
     * 
     */
    public RoadSurfaceConditionMeasurements createRoadSurfaceConditionMeasurements() {
        return new RoadSurfaceConditionMeasurements();
    }

    /**
     * Create an instance of {@link TpegJunction }
     * 
     */
    public TpegJunction createTpegJunction() {
        return new TpegJunction();
    }

    /**
     * Create an instance of {@link GeneralObstruction }
     * 
     */
    public GeneralObstruction createGeneralObstruction() {
        return new GeneralObstruction();
    }

    /**
     * Create an instance of {@link RoadsideReferencePointPrimaryLocation }
     * 
     */
    public RoadsideReferencePointPrimaryLocation createRoadsideReferencePointPrimaryLocation() {
        return new RoadsideReferencePointPrimaryLocation();
    }

    /**
     * Create an instance of {@link eu.datex2.schema._2_0rc1._2_0.MeasuredValue }
     * 
     */
    public eu.datex2.schema._2_0rc1._2_0.MeasuredValue createMeasuredValue() {
        return new eu.datex2.schema._2_0rc1._2_0.MeasuredValue();
    }

    /**
     * Create an instance of {@link RoadOrCarriagewayOrLaneManagement }
     * 
     */
    public RoadOrCarriagewayOrLaneManagement createRoadOrCarriagewayOrLaneManagement() {
        return new RoadOrCarriagewayOrLaneManagement();
    }

    /**
     * Create an instance of {@link AlertCMethod4PrimaryPointLocation }
     * 
     */
    public AlertCMethod4PrimaryPointLocation createAlertCMethod4PrimaryPointLocation() {
        return new AlertCMethod4PrimaryPointLocation();
    }

    /**
     * Create an instance of {@link VehicleHeadway }
     * 
     */
    public VehicleHeadway createVehicleHeadway() {
        return new VehicleHeadway();
    }

    /**
     * Create an instance of {@link GeneralNetworkManagement }
     * 
     */
    public GeneralNetworkManagement createGeneralNetworkManagement() {
        return new GeneralNetworkManagement();
    }

    /**
     * Create an instance of {@link LinearTrafficView }
     * 
     */
    public LinearTrafficView createLinearTrafficView() {
        return new LinearTrafficView();
    }

    /**
     * Create an instance of {@link HeaderInformation }
     * 
     */
    public HeaderInformation createHeaderInformation() {
        return new HeaderInformation();
    }

    /**
     * Create an instance of {@link SpeedPercentile }
     * 
     */
    public SpeedPercentile createSpeedPercentile() {
        return new SpeedPercentile();
    }

    /**
     * Create an instance of {@link PredefinedLocation }
     * 
     */
    public PredefinedLocation createPredefinedLocation() {
        return new PredefinedLocation();
    }

    /**
     * Create an instance of {@link TpegNamedOnlyArea }
     * 
     */
    public TpegNamedOnlyArea createTpegNamedOnlyArea() {
        return new TpegNamedOnlyArea();
    }

    /**
     * Create an instance of {@link GeneralInstructionToRoadUsers }
     * 
     */
    public GeneralInstructionToRoadUsers createGeneralInstructionToRoadUsers() {
        return new GeneralInstructionToRoadUsers();
    }

    /**
     * Create an instance of {@link AlertCLocation }
     * 
     */
    public AlertCLocation createAlertCLocation() {
        return new AlertCLocation();
    }

    /**
     * Create an instance of {@link TpegHeight }
     * 
     */
    public TpegHeight createTpegHeight() {
        return new TpegHeight();
    }

    /**
     * Create an instance of {@link Linear }
     * 
     */
    public Linear createLinear() {
        return new Linear();
    }

    /**
     * Create an instance of {@link VisibilityInformation }
     * 
     */
    public VisibilityInformation createVisibilityInformation() {
        return new VisibilityInformation();
    }

    /**
     * Create an instance of {@link CatalogueReference }
     * 
     */
    public CatalogueReference createCatalogueReference() {
        return new CatalogueReference();
    }

    /**
     * Create an instance of {@link WindInformation }
     * 
     */
    public WindInformation createWindInformation() {
        return new WindInformation();
    }

    /**
     * Create an instance of {@link VehicleCharacteristics }
     * 
     */
    public VehicleCharacteristics createVehicleCharacteristics() {
        return new VehicleCharacteristics();
    }

    /**
     * Create an instance of {@link TrafficFlow }
     * 
     */
    public TrafficFlow createTrafficFlow() {
        return new TrafficFlow();
    }

    /**
     * Create an instance of {@link ReroutingManagement }
     * 
     */
    public ReroutingManagement createReroutingManagement() {
        return new ReroutingManagement();
    }

    /**
     * Create an instance of {@link TransitInformation }
     * 
     */
    public TransitInformation createTransitInformation() {
        return new TransitInformation();
    }

    /**
     * Create an instance of {@link MultilingualStringValue }
     * 
     */
    public MultilingualStringValue createMultilingualStringValue() {
        return new MultilingualStringValue();
    }

    /**
     * Create an instance of {@link OffsetDistance }
     * 
     */
    public OffsetDistance createOffsetDistance() {
        return new OffsetDistance();
    }

    /**
     * Create an instance of {@link MeasurementSiteTable }
     * 
     */
    public MeasurementSiteTable createMeasurementSiteTable() {
        return new MeasurementSiteTable();
    }

    /**
     * Create an instance of {@link NonWeatherRelatedRoadConditions }
     * 
     */
    public NonWeatherRelatedRoadConditions createNonWeatherRelatedRoadConditions() {
        return new NonWeatherRelatedRoadConditions();
    }

    /**
     * Create an instance of {@link FilterExitManagement }
     * 
     */
    public FilterExitManagement createFilterExitManagement() {
        return new FilterExitManagement();
    }

    /**
     * Create an instance of {@link FilterReference }
     * 
     */
    public FilterReference createFilterReference() {
        return new FilterReference();
    }

    /**
     * Create an instance of {@link AbnormalTraffic }
     * 
     */
    public AbnormalTraffic createAbnormalTraffic() {
        return new AbnormalTraffic();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link LifeCycleManagement }
     * 
     */
    public LifeCycleManagement createLifeCycleManagement() {
        return new LifeCycleManagement();
    }

    /**
     * Create an instance of {@link AlertCMethod4SecondaryPointLocation }
     * 
     */
    public AlertCMethod4SecondaryPointLocation createAlertCMethod4SecondaryPointLocation() {
        return new AlertCMethod4SecondaryPointLocation();
    }

    /**
     * Create an instance of {@link TravelTimeValue }
     * 
     */
    public TravelTimeValue createTravelTimeValue() {
        return new TravelTimeValue();
    }

    /**
     * Create an instance of {@link ConstructionWorks }
     * 
     */
    public ConstructionWorks createConstructionWorks() {
        return new ConstructionWorks();
    }

    /**
     * Create an instance of {@link Management }
     * 
     */
    public Management createManagement() {
        return new Management();
    }

    /**
     * Create an instance of {@link RoadsideAssistance }
     * 
     */
    public RoadsideAssistance createRoadsideAssistance() {
        return new RoadsideAssistance();
    }

    /**
     * Create an instance of {@link AlertCArea }
     * 
     */
    public AlertCArea createAlertCArea() {
        return new AlertCArea();
    }

    /**
     * Create an instance of {@link TpegFramedPoint }
     * 
     */
    public TpegFramedPoint createTpegFramedPoint() {
        return new TpegFramedPoint();
    }

    /**
     * Create an instance of {@link AlertCMethod2Point }
     * 
     */
    public AlertCMethod2Point createAlertCMethod2Point() {
        return new AlertCMethod2Point();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Exchange }
     * 
     */
    public Exchange createExchange() {
        return new Exchange();
    }

    /**
     * Create an instance of {@link TpegAreaDescriptor }
     * 
     */
    public TpegAreaDescriptor createTpegAreaDescriptor() {
        return new TpegAreaDescriptor();
    }

    /**
     * Create an instance of {@link TimePeriodByHour }
     * 
     */
    public TimePeriodByHour createTimePeriodByHour() {
        return new TimePeriodByHour();
    }

    /**
     * Create an instance of {@link AlertCMethod2SecondaryPointLocation }
     * 
     */
    public AlertCMethod2SecondaryPointLocation createAlertCMethod2SecondaryPointLocation() {
        return new AlertCMethod2SecondaryPointLocation();
    }

    /**
     * Create an instance of {@link TpegJunctionPointDescriptor }
     * 
     */
    public TpegJunctionPointDescriptor createTpegJunctionPointDescriptor() {
        return new TpegJunctionPointDescriptor();
    }

    /**
     * Create an instance of {@link DisturbanceActivity }
     * 
     */
    public DisturbanceActivity createDisturbanceActivity() {
        return new DisturbanceActivity();
    }

    /**
     * Create an instance of {@link ReferenceSettings }
     * 
     */
    public ReferenceSettings createReferenceSettings() {
        return new ReferenceSettings();
    }

    /**
     * Create an instance of {@link Validity }
     * 
     */
    public Validity createValidity() {
        return new Validity();
    }

    /**
     * Create an instance of {@link Temperature }
     * 
     */
    public Temperature createTemperature() {
        return new Temperature();
    }

    /**
     * Create an instance of {@link RoadOperatorServiceDisruption }
     * 
     */
    public RoadOperatorServiceDisruption createRoadOperatorServiceDisruption() {
        return new RoadOperatorServiceDisruption();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link TpegLinearLocation }
     * 
     */
    public TpegLinearLocation createTpegLinearLocation() {
        return new TpegLinearLocation();
    }

    /**
     * Create an instance of {@link SpeedManagement }
     * 
     */
    public SpeedManagement createSpeedManagement() {
        return new SpeedManagement();
    }

    /**
     * Create an instance of {@link PredefinedLocationsPublication }
     * 
     */
    public PredefinedLocationsPublication createPredefinedLocationsPublication() {
        return new PredefinedLocationsPublication();
    }

    /**
     * Create an instance of {@link VehicleObstruction }
     * 
     */
    public VehicleObstruction createVehicleObstruction() {
        return new VehicleObstruction();
    }

    /**
     * Create an instance of {@link MeasuredDataPublication }
     * 
     */
    public MeasuredDataPublication createMeasuredDataPublication() {
        return new MeasuredDataPublication();
    }

    /**
     * Create an instance of {@link PollutionMeasurement }
     * 
     */
    public PollutionMeasurement createPollutionMeasurement() {
        return new PollutionMeasurement();
    }

    /**
     * Create an instance of {@link InfrastructureDamageObstruction }
     * 
     */
    public InfrastructureDamageObstruction createInfrastructureDamageObstruction() {
        return new InfrastructureDamageObstruction();
    }

    /**
     * Create an instance of {@link ElaboratedDataPublication }
     * 
     */
    public ElaboratedDataPublication createElaboratedDataPublication() {
        return new ElaboratedDataPublication();
    }

    /**
     * Create an instance of {@link PublicEvent }
     * 
     */
    public PublicEvent createPublicEvent() {
        return new PublicEvent();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link VehicleDetectionTime }
     * 
     */
    public VehicleDetectionTime createVehicleDetectionTime() {
        return new VehicleDetectionTime();
    }

    /**
     * Create an instance of {@link NumberOfAxlesCharacteristic }
     * 
     */
    public NumberOfAxlesCharacteristic createNumberOfAxlesCharacteristic() {
        return new NumberOfAxlesCharacteristic();
    }

    /**
     * Create an instance of {@link AxleSpacing }
     * 
     */
    public AxleSpacing createAxleSpacing() {
        return new AxleSpacing();
    }

    /**
     * Create an instance of {@link GroupOfPeopleInvolved }
     * 
     */
    public GroupOfPeopleInvolved createGroupOfPeopleInvolved() {
        return new GroupOfPeopleInvolved();
    }

    /**
     * Create an instance of {@link TrafficViewRecord }
     * 
     */
    public TrafficViewRecord createTrafficViewRecord() {
        return new TrafficViewRecord();
    }

    /**
     * Create an instance of {@link HumidityInformation }
     * 
     */
    public HumidityInformation createHumidityInformation() {
        return new HumidityInformation();
    }

    /**
     * Create an instance of {@link RoadsideReferencePoint }
     * 
     */
    public RoadsideReferencePoint createRoadsideReferencePoint() {
        return new RoadsideReferencePoint();
    }

    /**
     * Create an instance of {@link Humidity }
     * 
     */
    public Humidity createHumidity() {
        return new Humidity();
    }

    /**
     * Create an instance of {@link MeasurementSiteTablePublication }
     * 
     */
    public MeasurementSiteTablePublication createMeasurementSiteTablePublication() {
        return new MeasurementSiteTablePublication();
    }

    /**
     * Create an instance of {@link TemperatureInformation }
     * 
     */
    public TemperatureInformation createTemperatureInformation() {
        return new TemperatureInformation();
    }

    /**
     * Create an instance of {@link Situation }
     * 
     */
    public Situation createSituation() {
        return new Situation();
    }

    /**
     * Create an instance of {@link PoorEnvironmentConditions }
     * 
     */
    public PoorEnvironmentConditions createPoorEnvironmentConditions() {
        return new PoorEnvironmentConditions();
    }

    /**
     * Create an instance of {@link AlertCMethod4Point }
     * 
     */
    public AlertCMethod4Point createAlertCMethod4Point() {
        return new AlertCMethod4Point();
    }

    /**
     * Create an instance of {@link Visibility }
     * 
     */
    public Visibility createVisibility() {
        return new Visibility();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link RoadsideServiceDisruption }
     * 
     */
    public RoadsideServiceDisruption createRoadsideServiceDisruption() {
        return new RoadsideServiceDisruption();
    }

    /**
     * Create an instance of {@link TrafficStatusValue }
     * 
     */
    public TrafficStatusValue createTrafficStatusValue() {
        return new TrafficStatusValue();
    }

    /**
     * Create an instance of {@link Mobility }
     * 
     */
    public Mobility createMobility() {
        return new Mobility();
    }

    /**
     * Create an instance of {@link WinterDrivingManagement }
     * 
     */
    public WinterDrivingManagement createWinterDrivingManagement() {
        return new WinterDrivingManagement();
    }

    /**
     * Create an instance of {@link GroupOfVehiclesInvolved }
     * 
     */
    public GroupOfVehiclesInvolved createGroupOfVehiclesInvolved() {
        return new GroupOfVehiclesInvolved();
    }

    /**
     * Create an instance of {@link AnimalPresenceObstruction }
     * 
     */
    public AnimalPresenceObstruction createAnimalPresenceObstruction() {
        return new AnimalPresenceObstruction();
    }

    /**
     * Create an instance of {@link AlertCMethod4Linear }
     * 
     */
    public AlertCMethod4Linear createAlertCMethod4Linear() {
        return new AlertCMethod4Linear();
    }

    /**
     * Create an instance of {@link PointDestination }
     * 
     */
    public PointDestination createPointDestination() {
        return new PointDestination();
    }

    /**
     * Create an instance of {@link RoadsideReferencePointLinear }
     * 
     */
    public RoadsideReferencePointLinear createRoadsideReferencePointLinear() {
        return new RoadsideReferencePointLinear();
    }

    /**
     * Create an instance of {@link HeaviestAxleWeightCharacteristic }
     * 
     */
    public HeaviestAxleWeightCharacteristic createHeaviestAxleWeightCharacteristic() {
        return new HeaviestAxleWeightCharacteristic();
    }

    /**
     * Create an instance of {@link MaintenanceWorks }
     * 
     */
    public MaintenanceWorks createMaintenanceWorks() {
        return new MaintenanceWorks();
    }

    /**
     * Create an instance of {@link GroupOfLocationsByReference }
     * 
     */
    public GroupOfLocationsByReference createGroupOfLocationsByReference() {
        return new GroupOfLocationsByReference();
    }

    /**
     * Create an instance of {@link Accident }
     * 
     */
    public Accident createAccident() {
        return new Accident();
    }

    /**
     * Create an instance of {@link GroupOfNonOrderedLocations }
     * 
     */
    public GroupOfNonOrderedLocations createGroupOfNonOrderedLocations() {
        return new GroupOfNonOrderedLocations();
    }

    /**
     * Create an instance of {@link TpegOtherPointDescriptor }
     * 
     */
    public TpegOtherPointDescriptor createTpegOtherPointDescriptor() {
        return new TpegOtherPointDescriptor();
    }

    /**
     * Create an instance of {@link Impact }
     * 
     */
    public Impact createImpact() {
        return new Impact();
    }

    /**
     * Create an instance of {@link TrafficConcentration }
     * 
     */
    public TrafficConcentration createTrafficConcentration() {
        return new TrafficConcentration();
    }

    /**
     * Create an instance of {@link AlertCLinearByCode }
     * 
     */
    public AlertCLinearByCode createAlertCLinearByCode() {
        return new AlertCLinearByCode();
    }

    /**
     * Create an instance of {@link TpegNonJunctionPoint }
     * 
     */
    public TpegNonJunctionPoint createTpegNonJunctionPoint() {
        return new TpegNonJunctionPoint();
    }

    /**
     * Create an instance of {@link EnvironmentalObstruction }
     * 
     */
    public EnvironmentalObstruction createEnvironmentalObstruction() {
        return new EnvironmentalObstruction();
    }

    /**
     * Create an instance of {@link EquipmentOrSystemFault }
     * 
     */
    public EquipmentOrSystemFault createEquipmentOrSystemFault() {
        return new EquipmentOrSystemFault();
    }

    /**
     * Create an instance of {@link HeightCharacteristic }
     * 
     */
    public HeightCharacteristic createHeightCharacteristic() {
        return new HeightCharacteristic();
    }

    /**
     * Create an instance of {@link GrossWeightCharacteristic }
     * 
     */
    public GrossWeightCharacteristic createGrossWeightCharacteristic() {
        return new GrossWeightCharacteristic();
    }

    /**
     * Create an instance of {@link Itinerary.LocationContainedInItinerary }
     * 
     */
    public Itinerary.LocationContainedInItinerary createItineraryLocationContainedInItinerary() {
        return new Itinerary.LocationContainedInItinerary();
    }

    /**
     * Create an instance of {@link MultilingualString.Values }
     * 
     */
    public MultilingualString.Values createMultilingualStringValues() {
        return new MultilingualString.Values();
    }

    /**
     * Create an instance of {@link MeasurementSiteRecord.MeasurementSpecificCharacteristics }
     * 
     */
    public MeasurementSiteRecord.MeasurementSpecificCharacteristics createMeasurementSiteRecordMeasurementSpecificCharacteristics() {
        return new MeasurementSiteRecord.MeasurementSpecificCharacteristics();
    }

    /**
     * Create an instance of {@link SiteMeasurements.MeasuredValue }
     * 
     */
    public SiteMeasurements.MeasuredValue createSiteMeasurementsMeasuredValue() {
        return new SiteMeasurements.MeasuredValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link D2LogicalModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://datex2.eu/schema/2_0RC1/2_0", name = "d2LogicalModel")
    public JAXBElement<D2LogicalModel> createD2LogicalModel(D2LogicalModel value) {
        return new JAXBElement<D2LogicalModel>(_D2LogicalModel_QNAME, D2LogicalModel.class, null, value);
    }

}
