//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.22 at 01:45:09 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ifopt.org.uk/ifopt", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.org.ifopt.ifopt;
